#!/usr/bin/env bash
# Copyright (c) 2026 Eduardo Correia <ecorreia@apliant.com.br>
#
# This file is part of MsgBot. It is free software, licensed under the GNU
# Lesser General Public License v3.0 or later. See COPYING.LESSER and
# COPYING for details.
#
# SPDX-License-Identifier: LGPL-3.0-or-later

set -euo pipefail

cd "$(dirname "$0")"

# Ensure .env exists
if [[ ! -f .env ]]; then
    echo "ERROR: .env file not found. Copy .env.example and fill in your keys:"
    echo "  cp .env.example .env"
    exit 1
fi

# Give the web UI a fixed password the first time, so it doesn't change on
# every restart (without one, the bot generates a new one each start).
if ! grep -qE '^WEB_PASSWORD=.+' .env; then
    password=$(openssl rand -base64 18 2>/dev/null | tr -d '/+=' || head -c 18 /dev/urandom | base64 | tr -d '/+=')
    sed -i '/^WEB_PASSWORD=/d' .env
    printf '\n# Web UI login (generated by run.sh)\nWEB_PASSWORD=%s\n' "$password" >> .env
    echo "=== Generated a web UI password and saved it in .env ==="
    echo "    WEB_PASSWORD=$password"
fi

# Print where the web UI can be reached: the host port published for the bot.
print_access() {
    local port user ip
    port=$(docker compose config --format json bot 2>/dev/null \
        | grep -oE '"published": *"[0-9]+"' | grep -oE '[0-9]+' | head -n1 || true)
    port=${port:-8088}
    user=$(grep -E '^WEB_USERNAME=' .env | tail -n1 | cut -d= -f2- || true)
    ip=$(ip -4 route get 1.1.1.1 2>/dev/null | grep -oE 'src [0-9.]+' | cut -d' ' -f2 || true)
    [[ -n "$ip" ]] || ip=$(hostname -I 2>/dev/null | awk '{print $1}' || true)

    echo "=== MsgBot web UI ==="
    echo "    This machine:  http://localhost:$port"
    if [[ -n "$ip" ]]; then
        if grep -qi microsoft /proc/version 2>/dev/null; then
            echo "    WSL address:   http://$ip:$port   (from Windows, use localhost)"
        else
            echo "    Network:       http://$ip:$port"
        fi
    fi
    echo "    Login:         ${user:-admin} / WEB_PASSWORD in .env"
}

echo "=== Starting MsgBot stack ==="
if [[ " $* " == *" -d "* || " $* " == *" --detach "* ]]; then
    docker compose up "$@"
    print_access
else
    # Attached mode blocks until the stack stops, so print the address first.
    print_access
    docker compose up "$@"
fi
